version: '3.7'
services:
  database:
    image: postgres:12.2-alpine
    ports:
      - '5858:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - trust-postgres-data:/var/lib/postgresql/data:delegated
volumes:
  trust-postgres-data: